import type { Metadata } from "next";
import "./globals.css";
import SupabaseProvider from "@/context/SupabaseProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <body
      className={`antialiased`}
    >
    <SupabaseProvider>
      <div className={"w-svw min-h-[100dvh] bg-black flex justify-center"}>
        <div className={"w-full md:max-w-[500px] h-dvh bg-white"}>
          {children}
        </div>
      </div>
    </SupabaseProvider>
    </body>
    </html>
  );
}
