import type { Metadata } from "next";
import "./globals.css";
import SupabaseProvider from "@/context/SupabaseProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SupabaseProvider><div className={"w-screen h-screen bg-black flex justify-center"}>
          <div className={"w-full md:max-w-[500px] h-screen bg-white"}>
            {children}
          </div>
        </div></SupabaseProvider>
      </body>
    </html>
  );
}
